name: Mark Thomas
favicon: null
layout_spectrum: 0.12851764168590307
typography_spectrum: 0.055171821964904666
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.579585918225348
  lightness: 0.7449440779164433
  saturation: 0.3209450296126306
  rhythmicContrast: 0.71907589584589
purpose: []
